version: '3'
services:
  nginx:
    build:
      context: ./_nginx
    image: wkwok16/personal_nginx
    links:
        - node1:node1
    ports:
        - "80"
        - "443"
  node1:
    build:
      context: ./
    image: wkwok16/personal_site
    ports:
        - "3000"